package com.brunomoura.ecommerceapi.enums;

public enum ErrorCode {

    // JSON
    INVALID_REQUEST,

    // FIELDS
    INVALID_FIELDS,

    // AUTH
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCESS_DENIED,

    // ADDRESS
    ADDRESS_ALREADY_EXISTS,
    ADDRESS_NOT_FOUND,
    INVALID_ADDRESS_FIELD,
    LAST_ADDRESS_REMOVAL_NOT_ALLOWED,

    // USER
    CPF_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INVALID_CURRENT_PASSWORD,
    INVALID_DATE_OF_BIRTH,
    INVALID_RANGE_DATE,
    INVALID_USER_FIELD,
    USER_DELETED_CANNOT_BE_CHANGED,
    USER_NOT_FOUND,
    WEAK_PASSWORD,

    //INTERNAL
    UNEXPECTED_ERROR
}
